### ISSUE TITLE
Upgrade to Guzzle 6?

### ISSUE THREAD

**Issue by drupalnomad** [graze/guzzle-jsonrpc#17]
I use this package on Drupal 8, but composer can no longer resolve because Drupal needs Guzzle 6.

**Comment by sjparkinson** [comment]
Thanks for raising an issue :star:. I'll setup a new milestone for this.

If you're looking to contribute we'd love a PR, otherwise we'll look to make the change in the near future.

**Comment by drupalnomad** [comment]
Sorry - no time to help. I don't actually need this for several months.

https://github.com/guzzle/guzzle/blob/master/UPGRADING.md
