### ISSUE TITLE
Using differnet url paths after client object is created

### ISSUE THREAD

**Issue by prasanthsd** [graze/guzzle-jsonrpc#29]
Hi,

I tried using this with a RPC server which has different URL paths for certain methods. For example when im executing "method1" the url maybe http://domain/login and when in other cases it maybe http://domain/execute

Does this package support this or will this be added sometime in the future?

**Comment by h-bragg** [comment]
Hi,

Sorry for the looooong delay; I have recently started maintaining this project.

This is not supported very nicely out of the box, however all the requests being sent via `send` are just standard HTTP requests, so you can use the base Guzzle `RequestInterface` to modify the uri as such:

```php
$request = $client->request('id1', 'method1', ['data' => 'stuff'])->withUri(new Uri('http://domain/execute'));
$response = $client->send($request);
```
