### ISSUE TITLE
Missing ability to send array of requests

### ISSUE THREAD

**Issue by rockfridrich** [graze/guzzle-jsonrpc#37]
In JSON-RPC specification you can send an array or request and receive an array of responses. 
In some scenarios, it may slightly increase performance in the library will send N asynced HTTP requests with M JSON-RPC requests in each.

**Comment by h-bragg** [comment]
Hi, 

There are `->sendAll(array $requests)` and `->sendAllAsync(array $requests)` methods that handle sending batches or requests at once, and handle the multiple responses for each request.

**Comment by biggianteye** [comment]
From what I can see, that data you provided fits into the api call that Harry is suggesting. eg.

```php
$requests = [
    $client->request(
        '0x0abdace70d3790235af448c88547603b945604ea',
        'eth_call',
        [
            [
                'to' => '0x0abdace70d3790235af448c88547603b945604ea',
                'data' => '0x70a082310000000000000000000000000ad9fb61a07bac25625382b63693644497f1b204'
            ],
            'latest'
        ]
    ),
    // More requests here
];
$responses = $client->sendAll($requests);
```

Are you able to explain why you think that data would not work?
